name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Navigating to project directory..."
          cd /home/ec2-user/medFlow-patient-intake-telegram-bot || exit 1
          echo "Pulling latest changes..."
          git pull || exit 1
          echo "Installing dependencies..."
          npm install || exit 1
          echo "Restarting application with PM2..."
          pm2 restart all || exit 1
