name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to the bot directory
            cd medFlow-patient-intake-telegram-bot

            # Pull latest changes
            echo "Pulling latest changes from Git..."
            git stash
            git pull

            # Ensure the correct Node.js version is installed
            echo "Ensuring Node.js is installed..."
            nvm install 16.15.1
            nvm alias default 16.15.1

            # Update the environment variables in the .env file
            echo "Updating environment variables..."
            touch .env
            sed -i "/^TELEGRAM_BOT_TOKEN=/d" .env && echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            sed -i "/^PATIENT_FORM_BASE_URL=/d" .env && echo "PATIENT_FORM_BASE_URL=${{ secrets.PATIENT_FORM_BASE_URL }}" >> .env
            sed -i "/^PROD_TELEGRAM_BOT_KEY=/d" .env && echo "PROD_TELEGRAM_BOT_KEY=${{ secrets.PROD_TELEGRAM_BOT_KEY }}" >> .env

            # Install dependencies
            echo "Installing dependencies..."
            npm install

            # Check if the bot is running and gracefully stop it if it is
            if pm2 describe telegram-bot > /dev/null; then
              echo "Stopping existing bot..."
              pm2 stop telegram-bot
              pm2 delete telegram-bot
            else
              echo "Bot is not running."
            fi

            # Start the bot with PM2 and ensure logs are clear
            echo "Starting the bot with PM2..."
            pm2 start npm --name "telegram-bot" -- start --log-date-format "YYYY-MM-DD HH:mm Z"
            
            # Ensure PM2 process list is saved for restart on reboot
            echo "Saving PM2 process list..."
            pm2 save

            # Display PM2 status for debugging
            echo "PM2 process list:"
            pm2 list