name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd medFlow-patient-intake-telegram-bot
            git pull
            nvm install 16.15.1
            nvm alias default 16.15.1

            # Ensure .env file exists
            touch .env

            # Update or append keys in the .env file
            sed -i "/^TELEGRAM_BOT_TOKEN=/d" .env && echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            sed -i "/^PATIENT_FORM_BASE_URL=/d" .env && echo "PATIENT_FORM_BASE_URL=${{ secrets.PATIENT_FORM_BASE_URL }}" >> .env
            sed -i "/^PROD_TELEGRAM_KEY=/d" .env && echo "PROD_TELEGRAM_KEY=${{ secrets.PROD_TELEGRAM_KEY }}" >> .env

            npm install

            # Stop the bot if it's already running
            pm2 describe telegram-bot && pm2 stop telegram-bot || echo "Bot is not running"

            # Start the bot in the background using pm2
            pm2 start npm --name "telegram-bot" -- start

            # Save the pm2 process list for auto-restart on reboot
            pm2 save