name: Stop Telegram Bot

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  stop_bot:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Debug SSH Key
        run: echo "${{ secrets.EC2_SSH_KEY }}" | wc -c

      - name: Stop the Telegram Bot
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd medFlow-patient-intake-telegram-bot
            ~/.nvm/versions/node/v16.15.1/bin/pm2 stop telegram-bot || echo "Telegram bot is already stopped or not running"