name: Stop Telegram Bot

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  stop_bot:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Debug SSH Key
        run: echo "${{ secrets.EC2_SSH_KEY }}" | wc -c

      - name: Stop the Telegram Bot
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd medFlow-patient-intake-telegram-bot
            pm2 stop telegram-bot || echo "Telegram bot is already stopped or not running"
            pm2 delete telegram-bot || echo "No telegram-bot processes to delete"
            pm2 save