name: Stop Telegram Bot

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  stop_bot:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Debug SSH Key
        run: echo "${{ secrets.EC2_SSH_KEY }}" | wc -c

      - name: Stop the Telegram Bot
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            export PATH="$HOME/.nvm/versions/node/v16.15.1/bin:$PATH"
            cd $HOME/medFlow-patient-intake-telegram-bot
            if command -v pm2 &> /dev/null; then
              echo "PM2 is available"
              pm2 stop telegram-bot || echo "Telegram bot is already stopped or not running"
              pm2 delete telegram-bot || echo "No telegram-bot processes to delete"
              pm2 save
            else
              echo "PM2 is not available. Attempting to install..."
              npm install -g pm2
              if command -v pm2 &> /dev/null; then
                echo "PM2 installed successfully"
                pm2 stop telegram-bot || echo "Telegram bot is already stopped or not running"
                pm2 delete telegram-bot || echo "No telegram-bot processes to delete"
                pm2 save
              else
                echo "Failed to install PM2. Please check your Node.js installation."
              fi
            fi